stages:
  download:
    cmd: Rscript stages/build.R
    deps:
    - stages/build.R
    - stages/chrome.R
    outs:
    - cache/drug
    - list
    - data
  make_script:
    cmd: ./stages/conversionJsonParquet.sh
    deps:
    - list
    - stages/conversionJsonParquet.sh
    outs:
    - stages/commands.sh
  execute:
    cmd: ./stages/commands.sh
    deps:
    - stages/commands.sh
    - cache/drug
    outs:
    - brick
    - cache/tmp
  docs:
    cmd: ./stages/download_docs.sh
    outs:
    - docs/reference
